### ISSUE TITLE
Sales Order Grid is empty after data migration

### ISSUE THREAD

**Issue by Vincenkt** [magento/data-migration-tool-ce#11]
I've made data migration from Magento 1 to Magento 2 using data-migration-tool according to this article http://devdocs.magento.com/guides/v2.0/migration/migration-migrate-data.html. Orders migrated successfully, but Sales Order grid is empty - this happened because sales_flat_order_grid (from magento 1) and sales_order_grid (from magento 2) tables are ignored in the mapping file by default, like this.

<destination>
    <document_rules>
        <ignore>
           <document>sales_order_grid</document>
        </ignore>
    </document_rules>
</destination>
These tables have different columns (magento2's table has 10 additional columns), and they can't be moved just like that. Is there any way to re-build sales_order_grid table, based on another tables data? I've cleaned cache and made all reindexes, with no luck.

**Comment by yaronish** [comment]
Hi, Vinsenkt
OrderGrids Step is responsible for grid migration.
Can you confirm that next code is present in your config.xml file and this step is being executed during migration?
        <step title="OrderGrids Step">
            <integrity>Migration\Step\OrderGrids\Integrity</integrity>
            <data>Migration\Step\OrderGrids\Data</data>
            <volume>Migration\Step\OrderGrids\Volume</volume>
        </step>
