### ISSUE TITLE
Url_rewrite step error

### ISSUE THREAD

**Issue by Vincenkt** [magento/data-migration-tool-ce#14]
I'm facing a problem in url_rewrite step.
Can you help me fix this issue?
![1](https://cloud.githubusercontent.com/assets/16131502/11613866/dac8c740-9c62-11e5-9631-45284f45bebe.png)

**Comment by jgmage** [comment]
Try deleting any custom urls in your source database.  This resolved this error for me, not sure if it is the same for you.

delete from core_url_rewrite where is_system = 0;

**Comment by Vincenkt** [comment]
Hi Jgmage,

Thanks for your help. I did see a notice in log fil.
" Mismatch of entities in the document: url_rewrite".
Do you have any idea?
