### ISSUE TITLE
Migration process breaks double byte characters

### ISSUE THREAD

**Issue by HirokazuNishi** [magento/data-migration-tool-ce#18]
Please see attached 2 images. One is M1, and the other is M2.
I created one product on M1 with double byte characters, and executed migration process.
After it completed, I checked product data on M2. Its attributes data with double byte characters are broken.

Can't this tool use for double byte characters?
Of course I can use double byte characters for products or any other data on M2 via cli or admin panel.

![m1 product](https://cloud.githubusercontent.com/assets/124136/11718294/9019cdc8-9f98-11e5-997e-0538d6b1663f.png)
![m2 product](https://cloud.githubusercontent.com/assets/124136/11718295/901e88ae-9f98-11e5-96d2-bdc666289efa.png)

**Comment by dgoyachev** [comment]
Have same issue - russian letters breaks while importing 1.9.2.1 -> 2.0.0

**Comment by HirokazuNishi** [comment]
I made PR #28.
It was caused by missing option parameters for mysql connection.
