### ISSUE TITLE
Mysql server has gone away when data migration step: Map Step

### ISSUE THREAD

**Issue by Vincenkt** [magento/data-migration-tool-ce#24]
I'm migrating data from magento 1.7.0.2 to magento 2 and I have a problem.
Any help?
![screenshot_1](https://cloud.githubusercontent.com/assets/16131502/11804050/faf12acc-a332-11e5-88f1-0ad3b542969b.png)

**Comment by karlsminton** [comment]
I'm having the same issue, in 1.7.0.2 to 2.0.7
