### ISSUE TITLE
1.9.2 Migration

### ISSUE THREAD

**Issue by rkhoury82** [magento/data-migration-tool-ce#3]
Is there any technical reason this won't work for CE 1.9.2 ? Or is it best to wait until compatibility is confirmed?

**Comment by ilol** [comment]
Hi @rkhoury82, you have mentioned the newest CE version of Magento 1.x, and we just had not assembled the proper _map_ file for this version yet. 
To proceed migration from this version you should modify the map file using our inbound "debugger": follow the instruction from _log_ file. The database changes are not very deep.

Welcome to create pull-request and update our basic package with new map file CE1.9.2 -> CE2.0.

**Comment by craigcarnell** [comment]
@ilol Ditto please update to support 1.9.2.1

**Comment by Caprico85** [comment]
Commit 092857123e864951beee3041362920a0b0375c79 supports migration for Magento 1.9.2.2.

**Comment by ilol** [comment]
@Caprico85 thanks!
@rkhoury82, would you close the ticket?
