### ISSUE TITLE
Delta mode is stuck in the loop

### ISSUE THREAD

**Issue by ivanweiler** [magento/data-migration-tool-ce#4]
Hello all,

When running `php migrate delta --config=myconfigpath.xml` process is stuck in the loop and stopped only with ctrl-c. Every time delta update is done, there is a message "Automatic restart in 5 sec. Use CTRL-C to abort" and it's started again, is this on purpose?

autoRestart property is never decreased at
https://github.com/magento/data-migration-tool-ce/blob/master/src/Migration/Mode/Delta.php#L123

**Comment by victor-v-rad** [comment]
Hi Ivan,
According to the official documentation
http://devdocs.magento.com/guides/v2.0/migration/migration-migrate-delta.html
it was done on purpose.
Reason: on live store orders, customers and other entities are created constantly and the migration tool in delta mode will catch it and migrate on the fly every 5 sec

**Comment by ivanweiler** [comment]
Makes sense, thanks for explaining ;)

**Comment by balex13** [comment]
Трщшс
4 сент. 2015 г. 15:06 пользователь "Ivan Weiler" <notifications@github.com>
написал:

**Comment by ilol** [comment]
@ivanweiler would you close the issue?
