### ISSUE TITLE
Admin users not copied across?

### ISSUE THREAD

**Issue by craigcarnell** [magento/data-migration-tool-ce#40]

**Comment by victor-v-rad** [comment]
Unfortunately not. See the [documentation](http://devdocs.magento.com/guides/v2.0/migration/migration-manually.html)

**Comment by ilol** [comment]
@craigcarnell please, close the issue.

**Comment by craigcarnell** [comment]
@ilol This is a big issue for our organization as it has a lot of existing users, but I will write a script for it

**Comment by ilol** [comment]
That is good. You can make contribution to our Migration Tool or create extension.

**Comment by PascalBrouwers** [comment]
@craigcarnell did you manage to make a script for it?
