### ISSUE TITLE
Integrity checkstep: EAV Step - Error also the field is ignored

### ISSUE THREAD

**Issue by andidhouse** [magento/data-migration-tool-ce#45]
We have the following error when starting the data migration:

[2016-01-11 15:43:09][INFO][mode: data][stage: integrity check][step: EAV Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-11 15:43:09][ERROR]: Source fields are missing or not mapped. Document: catalog_eav_attribute. Fields: layered_navigation_canonical

We double checked but ignored the field (with many others) in the map.xml file - all other fields we put in are successfully ignored but this one not.

<ignore><field>catalog_eav_attribute.layered_navigation_canonical</field></ignore>

Is there another possibility to ignore this field?

PS: When we delete it from the source database all works.
![bildschirmfoto 2016-01-11 um 16 45 57](https://cloud.githubusercontent.com/assets/16196483/12238650/5ac1f5c8-b885-11e5-8989-1948d7aac60d.png)

**Comment by victor-v-rad** [comment]
Hi,

I assume you should add ignore tag to `etc/ce-to-ce/map-eav.xml.dist` file

**Comment by andidhouse** [comment]
many thanks! your are right and this solved the issue!

**Comment by hamdansalik** [comment]
I have the same error migration from EE 1.13.0.2 to ECloud , after commit still same error
