### ISSUE TITLE
data migration step error

### ISSUE THREAD

**Issue by Vincenkt** [magento/data-migration-tool-ce#9]
Hi there,

I am facing a problem when migrating data. Please see this link http://prntscr.com/99ruq6.
Do you have any idea?
Thank you very much!

**Comment by quynhvv** [comment]
@Vincenkt: Sorry, It is out of scope support.
You can try in other way with:
https://github.com/ubertheme/module-ubdatamigration

Or 

https://docs.google.com/document/d/1FmJfDIm8u09m8T9jcCL38t3vRxcKbS7DMltaA2WFUI8/edit

Regards,
quynhvv

**Comment by Vincenkt** [comment]
Hi Quynhvv,

Thanks for your help. However, I have a problem when in step 3. Please check link http://prntscr.com/99sd0m.
Thank you so much!

**Comment by quynhvv** [comment]
@Vincenkt :
What module of this tool you are using?
What versions of your Magento 1 and Magento 2 in your working?
Regards,
quynhvv

**Comment by Vincenkt** [comment]
Hi quynhvv,

I'm using magento 1.9.1.0 and mageno ce 2.0.
